# Generated by Django 3.2 on 2021-06-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=70)),
                ('flag', models.CharField(max_length=170)),
                ('country', models.CharField(max_length=70)),
            ],
        ),
    ]
